To github.com:BodihTao/fmz.git
   da760bf..5c0d330  master -> master
To github.com:BodihTao/fmz.git
   5c0d330..2ad223c  master -> master
To github.com:BodihTao/fmz.git
   2ad223c..2a3c65a  master -> master
To github.com:BodihTao/fmz.git
   2a3c65a..d7a65d6  master -> master
To github.com:BodihTao/fmz.git
   d7a65d6..7961fbe  master -> master
To github.com:BodihTao/fmz.git
   7961fbe..be89071  master -> master
To github.com:BodihTao/fmz.git
   be89071..848de9a  master -> master
To github.com:BodihTao/fmz.git
   848de9a..2ee1ddc  master -> master
To github.com:BodihTao/fmz.git
   2ee1ddc..3fd10e2  master -> master
To github.com:BodihTao/fmz.git
   3fd10e2..5b32ff6  master -> master
To github.com:BodihTao/fmz.git
   5b32ff6..2c2b600  master -> master
To github.com:BodihTao/fmz.git
   2c2b600..e025894  master -> master
To github.com:BodihTao/fmz.git
   e025894..29716e1  master -> master
To github.com:BodihTao/fmz.git
   29716e1..fd3fe09  master -> master
To github.com:BodihTao/fmz.git
   fd3fe09..6e17aa0  master -> master
To github.com:BodihTao/fmz.git
   6e17aa0..9610340  master -> master
To github.com:BodihTao/fmz.git
   9610340..e0dd078  master -> master
To github.com:BodihTao/fmz.git
   e0dd078..2dd773c  master -> master
To github.com:BodihTao/fmz.git
   2dd773c..fa5911a  master -> master
Traceback (most recent call last):
  File "sina_blog_crawler.py", line 59, in <module>
    htmlText = get_html_body(urlInput)
  File "sina_blog_crawler.py", line 52, in get_html_body
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
To github.com:BodihTao/fmz.git
   fa5911a..1d05331  master -> master
To github.com:BodihTao/fmz.git
   1d05331..f6a9522  master -> master
To github.com:BodihTao/fmz.git
   f6a9522..9c6becb  master -> master
To github.com:BodihTao/fmz.git
   9c6becb..0869779  master -> master
To github.com:BodihTao/fmz.git
   0869779..7ba8a8f  master -> master
To github.com:BodihTao/fmz.git
   7ba8a8f..b0be714  master -> master
To github.com:BodihTao/fmz.git
   b0be714..0949fbc  master -> master
To github.com:BodihTao/fmz.git
   0949fbc..b426291  master -> master
To github.com:BodihTao/fmz.git
   b426291..6ed77ed  master -> master
To github.com:BodihTao/fmz.git
   6ed77ed..95b2da6  master -> master
To github.com:BodihTao/fmz.git
   95b2da6..dc7267e  master -> master
To github.com:BodihTao/fmz.git
   dc7267e..a2ad40f  master -> master
To github.com:BodihTao/fmz.git
   a2ad40f..c258c05  master -> master
To github.com:BodihTao/fmz.git
   c258c05..fe901a1  master -> master
To github.com:BodihTao/fmz.git
   fe901a1..bcac149  master -> master
To github.com:BodihTao/fmz.git
   bcac149..b5904b7  master -> master
To github.com:BodihTao/fmz.git
   b5904b7..72232a0  master -> master
To github.com:BodihTao/fmz.git
   72232a0..37a1fb8  master -> master
To github.com:BodihTao/fmz.git
   37a1fb8..7f0a3f6  master -> master
To github.com:BodihTao/fmz.git
   7f0a3f6..b0de13a  master -> master
To github.com:BodihTao/fmz.git
   b0de13a..57896d9  master -> master
To github.com:BodihTao/fmz.git
   57896d9..b548aa4  master -> master
ssh: Could not resolve hostname github.com: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
To github.com:BodihTao/fmz.git
   b548aa4..eb6e362  master -> master
To github.com:BodihTao/fmz.git
   eb6e362..de40b7a  master -> master
Traceback (most recent call last):
  File "sina_blog_crawler.py", line 96, in <module>
    htmlText = get_html_body(strURL)
  File "sina_blog_crawler.py", line 52, in get_html_body
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 54] Connection reset by peer
To github.com:BodihTao/fmz.git
   de40b7a..bc2a899  master -> master
To github.com:BodihTao/fmz.git
   bc2a899..e6fe345  master -> master
Traceback (most recent call last):
  File "sina_blog_crawler.py", line 59, in <module>
    htmlText = get_html_body(urlInput)
  File "sina_blog_crawler.py", line 52, in get_html_body
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
To github.com:BodihTao/fmz.git
   e6fe345..2687bad  master -> master
To github.com:BodihTao/fmz.git
   2687bad..ecd7f33  master -> master
To github.com:BodihTao/fmz.git
   ecd7f33..5b6b6ee  master -> master
Traceback (most recent call last):
  File "sina_blog_crawler.py", line 96, in <module>
    htmlText = get_html_body(strURL)
  File "sina_blog_crawler.py", line 52, in get_html_body
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 54] Connection reset by peer
To github.com:BodihTao/fmz.git
   5b6b6ee..8a08e95  master -> master
To github.com:BodihTao/fmz.git
   8a08e95..6c468f5  master -> master
To github.com:BodihTao/fmz.git
   6c468f5..25ff108  master -> master
To github.com:BodihTao/fmz.git
   25ff108..36c8731  master -> master
To github.com:BodihTao/fmz.git
   36c8731..8659086  master -> master
To github.com:BodihTao/fmz.git
   8659086..c9ed6bb  master -> master
To github.com:BodihTao/fmz.git
   c9ed6bb..46f48fc  master -> master
To github.com:BodihTao/fmz.git
   46f48fc..8185b7e  master -> master
To github.com:BodihTao/fmz.git
   8185b7e..30c073b  master -> master
To github.com:BodihTao/fmz.git
   30c073b..7649c46  master -> master
Traceback (most recent call last):
  File "sina_blog_crawler.py", line 59, in <module>
    htmlText = get_html_body(urlInput)
  File "sina_blog_crawler.py", line 52, in get_html_body
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
Traceback (most recent call last):
  File "sina_blog_crawler.py", line 59, in <module>
    htmlText = get_html_body(urlInput)
  File "sina_blog_crawler.py", line 52, in get_html_body
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
To github.com:BodihTao/fmz.git
   7649c46..30190e7  master -> master
To github.com:BodihTao/fmz.git
   30190e7..0a73c62  master -> master
To github.com:BodihTao/fmz.git
   0a73c62..ed6cd73  master -> master
To github.com:BodihTao/fmz.git
   ed6cd73..b6befca  master -> master
To github.com:BodihTao/fmz.git
   b6befca..bf1237a  master -> master
To github.com:BodihTao/fmz.git
   bf1237a..642dfb7  master -> master
To github.com:BodihTao/fmz.git
   642dfb7..4adade2  master -> master
To github.com:BodihTao/fmz.git
   4adade2..d47f56d  master -> master
To github.com:BodihTao/fmz.git
   d47f56d..1b26d14  master -> master
To github.com:BodihTao/fmz.git
   1b26d14..99d77ed  master -> master
To github.com:BodihTao/fmz.git
   99d77ed..ecfaf40  master -> master
To github.com:BodihTao/fmz.git
   ecfaf40..01d0b8d  master -> master
To github.com:BodihTao/fmz.git
   01d0b8d..0f488b4  master -> master
To github.com:BodihTao/fmz.git
   0f488b4..b713e98  master -> master
To github.com:BodihTao/fmz.git
   b713e98..d029af4  master -> master
To github.com:BodihTao/fmz.git
   d029af4..58ff318  master -> master
To github.com:BodihTao/fmz.git
   58ff318..8409cdd  master -> master
To github.com:BodihTao/fmz.git
   8409cdd..830eb62  master -> master
To github.com:BodihTao/fmz.git
   830eb62..74a6bd8  master -> master
Traceback (most recent call last):
  File "sina_blog_crawler.py", line 96, in <module>
    htmlText = get_html_body(strURL)
  File "sina_blog_crawler.py", line 52, in get_html_body
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 54] Connection reset by peer
Traceback (most recent call last):
  File "sina_blog_crawler.py", line 70, in <module>
    htmlText = get_html_body(k_sina_article_url + strUID + "_0_1.html")
  File "sina_blog_crawler.py", line 52, in get_html_body
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 54] Connection reset by peer
Traceback (most recent call last):
  File "sina_blog_crawler.py", line 96, in <module>
    htmlText = get_html_body(strURL)
  File "sina_blog_crawler.py", line 52, in get_html_body
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 54] Connection reset by peer
To github.com:BodihTao/fmz.git
   74a6bd8..aa3ff18  master -> master
To github.com:BodihTao/fmz.git
   aa3ff18..7de1174  master -> master
To github.com:BodihTao/fmz.git
   7de1174..4c976f3  master -> master
To github.com:BodihTao/fmz.git
   4c976f3..5157e7d  master -> master
To github.com:BodihTao/fmz.git
   5157e7d..23c6bd6  master -> master
To github.com:BodihTao/fmz.git
   23c6bd6..26a3ce1  master -> master
Traceback (most recent call last):
  File "sina_blog_crawler.py", line 96, in <module>
    htmlText = get_html_body(strURL)
  File "sina_blog_crawler.py", line 52, in get_html_body
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 60] Operation timed out>
To github.com:BodihTao/fmz.git
   26a3ce1..311c868  master -> master
Warning: Permanently added the RSA host key for IP address '192.30.255.112' to the list of known hosts.
To github.com:BodihTao/fmz.git
   311c868..b798523  master -> master
To github.com:BodihTao/fmz.git
   b798523..57e6acb  master -> master
To github.com:BodihTao/fmz.git
   57e6acb..2a2c9ae  master -> master
To github.com:BodihTao/fmz.git
   2a2c9ae..a576aa6  master -> master
Traceback (most recent call last):
  File "sina_blog_crawler.py", line 59, in <module>
    htmlText = get_html_body(urlInput)
  File "sina_blog_crawler.py", line 52, in get_html_body
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
To github.com:BodihTao/fmz.git
   a576aa6..a623b7d  master -> master
To github.com:BodihTao/fmz.git
   a623b7d..8e4880a  master -> master
To github.com:BodihTao/fmz.git
   8e4880a..2a20ed7  master -> master
To github.com:BodihTao/fmz.git
   2a20ed7..d8e5d18  master -> master
Traceback (most recent call last):
  File "sina_blog_crawler.py", line 59, in <module>
    htmlText = get_html_body(urlInput)
  File "sina_blog_crawler.py", line 52, in get_html_body
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
To github.com:BodihTao/fmz.git
   d8e5d18..7fcd660  master -> master
To github.com:BodihTao/fmz.git
   7fcd660..ad6a8e1  master -> master
To github.com:BodihTao/fmz.git
   ad6a8e1..a0a1e0e  master -> master
To github.com:BodihTao/fmz.git
   a0a1e0e..c4c5a7f  master -> master
To github.com:BodihTao/fmz.git
   c4c5a7f..4626b72  master -> master
Traceback (most recent call last):
  File "sina_blog_crawler.py", line 96, in <module>
    htmlText = get_html_body(strURL)
  File "sina_blog_crawler.py", line 52, in get_html_body
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 54] Connection reset by peer
Traceback (most recent call last):
  File "sina_blog_crawler.py", line 70, in <module>
    htmlText = get_html_body(k_sina_article_url + strUID + "_0_1.html")
  File "sina_blog_crawler.py", line 52, in get_html_body
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 51] Network is unreachable>
To github.com:BodihTao/fmz.git
   4626b72..f0d2705  master -> master
To github.com:BodihTao/fmz.git
   f0d2705..44fe181  master -> master
To github.com:BodihTao/fmz.git
   44fe181..549a449  master -> master
To github.com:BodihTao/fmz.git
   549a449..6adfb98  master -> master
To github.com:BodihTao/fmz.git
   6adfb98..9966d0d  master -> master
To github.com:BodihTao/fmz.git
   9966d0d..6ae7ebf  master -> master
To github.com:BodihTao/fmz.git
   6ae7ebf..755a98b  master -> master
To github.com:BodihTao/fmz.git
   755a98b..8c263f7  master -> master
To github.com:BodihTao/fmz.git
   8c263f7..4e8061c  master -> master
To github.com:BodihTao/fmz.git
   4e8061c..39dca8d  master -> master
To github.com:BodihTao/fmz.git
   39dca8d..32150c1  master -> master
